<?php include "../components/header.phtml" ?>

<?php include "../components/banner.phtml" ?>

<div class="container">
    <article>
        <h3>Por Talissa Andrade | 14-05</h3>
        <h1>TITULO DO POST</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut dolore et harum impedit ipsa libero maiores minima qui, rem temporibus. Aut corporis hic, in ipsa natus officia placeat ut voluptate.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut dolore et harum impedit ipsa libero maiores minima qui, rem temporibus. Aut corporis hic, in ipsa natus officia placeat ut voluptate.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut dolore et harum impedit ipsa libero maiores minima qui, rem temporibus. Aut corporis hic, in ipsa natus officia placeat ut voluptate.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut dolore et harum impedit ipsa libero maiores minima qui, rem temporibus. Aut corporis hic, in ipsa natus officia placeat ut voluptate.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut dolore et harum impedit ipsa libero maiores minima qui, rem temporibus. Aut corporis hic, in ipsa natus officia placeat ut voluptate.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut dolore et harum impedit ipsa libero maiores minima qui, rem temporibus. Aut corporis hic, in ipsa natus officia placeat ut voluptate.</p>
    </article>
</div>

<?php include "../components/footer.phtml"?>
