<div class="carousel-container">
    <div id="carousel" class="carousel slide" data-ride="carouselkkkk">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <span class="carousel-tag">
                    Solutions
                </span>
                <img src="../media/image/article.jpg">
                <div class="carousel-caption d-none d-md-block">
                    <div class="carousel-title">
                        <div class="carousel-info">
                            <span class="author">
                                <h3>Por Talissa Andrade</h3>
                            </span> |
                            <span class="date">04-05</span>
                        </div>
                        <h5>"Como fazer o seu blog aumentar a sua visibilidade na internet."</h5>
                    </div>
                    <div class="carousel-description">
                        <p>Vivemos na era da internet onde somos atacados por anúncios de lojas de roupas, alimentos, servicos e eventos além de sites onde há sites que disponibilizam conteúdo...</p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <span class="carousel-tag">
                    Solutions
                </span>
                <img src="../media/image/article.jpg">
                <div class="carousel-caption d-none d-md-block">
                    <div class="carousel-title">
                        <div class="carousel-info">
                            <span class="author">
                                <h3>Por Talissa Andrade</h3>
                            </span> |
                            <span class="date">04-05</span>
                        </div>
                        <h5>"Como fazer o seu blog aumentar a sua visibilidade na internet."</h5>
                    </div>
                    <div class="carousel-description">
                        <p>Vivemos na era da internet onde somos atacados por anúncios de lojas de roupas, alimentos, servicos e eventos além de sites onde há sites que disponibilizam conteúdo...</p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <span class="carousel-tag">
                    Solutions
                </span>
                <img src="../media/image/article.jpg">
                <div class="carousel-caption d-none d-md-block">
                    <div class="carousel-title">
                        <div class="carousel-info">
                            <span class="author">
                                <h3>Por Talissa Andrade</h3>
                            </span> |
                            <span class="date">04-05</span>
                        </div>
                        <h5>"Como fazer o seu blog aumentar a sua visibilidade na internet."</h5>
                    </div>
                    <div class="carousel-description">
                        <p>Vivemos na era da internet onde somos atacados por anúncios de lojas de roupas, alimentos, servicos e eventos além de sites onde há sites que disponibilizam conteúdo...</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="carousel-dots">
            <ol class="carousel-indicators">
                <li data-target="#carousel" data-slide-to="0" class="active"></li>
                <li data-target="#carousel" data-slide-to="1"></li>
                <li data-target="#carousel" data-slide-to="2"></li>
            </ol>
        </div>
    </div>
</div>