<footer class="footer">
    <div class="row footer-container">
        <div class="col-sm-6 information">
            <img src="./../media/logo/logo-white.png" alt="Logo Easy Campaign">
            <?php include "components/navigation.phtml"?>
        </div>
        <div class="col-sm-6 social-network">
            <div class="align-vertical wrapper">
                <h3>Siga nós</h3>
                <nav class="navbar navbar-light">
                    <a class="navbar-brand" href="#">
                        <i class="fab fa-facebook-square"></i>
                    </a>
                    <a class="navbar-brand" href="#">
                        <i class="fab fa-twitter-square"></i>
                    </a>
                    <a class="navbar-brand" href="#">
                        <i class="fab fa-instagram"></i>
                    </a>
                </nav>
            </div>
        </div>
    </div>
    <div class="row copyright">
        <p>2019 Easy Campaign. Todos os direitos reservados.</p>
    </div>
</footer>
</body>
</html>